"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[ui]
pager = "delta --color-only --line-numbers"
diff-formatter = ":git"
default-command = ["log", "--no-pager"]

[alias]
l = ["log", "--no-pager"]

[user]
name = "seroperson"
email = "seroperson@gmail.com"

[signing]
behavior = "own"
backend = "gpg"
key = "0B3C08C5FD554A20"
